sensor_settings:
  camera:
    resolution: [640, 480]
    frame_rate: 30
  lidar:
    range: 10.0
    angle: 360

joint_limits:
  arm_joint_1:
    min: -1.57
    max: 1.57
  arm_joint_2:
    min: -1.57
    max: 1.57
  gripper_joint:
    min: 0.0
    max: 0.1

robot_parameters:
  max_speed: 0.5
  acceleration: 0.2
  battery_capacity: 100.0
